server:
    port: 5000

spring:
    application:
        name: apiboard
    datasource:
        url: jdbc:mariadb://10.12.9.4:3307/hsk_rest_api
        # url: jdbc:mariadb://127.0.0.1:3307/hsk_rest_api
        username: JavaHSK
        password: Java1234
        driver-class-name: org.mariadb.jdbc.Driver
    thymeleaf:
        cache: false
        prefix: classpath:/templates/
        suffix: .html
    jpa:
        database-platform: org.hibernate.dialect.MariaDBDialect
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                '[show_sql]': true
                '[format_sql]': true

logging:
    level:
        '[org.hibernate.SQL]': DEBUG
        '[org.hibernate.type.descriptor.sql]': TRACE